export const InspectField = {
    throw_box_video: '摔箱检测视频',
    appearance_video: '外观检测视频',
    functions_video: '功能性检测视频',
    bearing_test_video: '承重检测视频',
    water_content_test_video: '含水量检测视频',
    factory_sample_room: '工厂样品间图片',
    outer_box_pic: '唛头',
    bar_code_pic: '条码图片',
    factory_other: '工厂其他图片',
    gross_weight_pic: '毛重图片',
    product_detail_pic: '产品细节图片',
    instructions_pic: '说明书图片',
    screws_pic: '螺丝包图片',
    product_wholes_pic: '产品整体图',
    product_size_pic: '产品尺寸图',
    appearance_pic: '外观检测图片',
    functions_pic: '功能性测试图片',
    summary_pic: '总结图片',
    inspection_require_pic: '验货要求图片',
    throw_box: '摔箱图片',
    size_pic: '尺寸图片',
    size_pic_length: '外箱尺寸长图片',
    size_pic_width: '外箱尺寸宽图片',
    size_pic_height: '外箱尺寸高图片',
    packing_pic: '包装图片',
    product_place_pic: '摆放图',
    instructions_and_accessories_pic: '说明书和附件图片',
    over_all_pic: '',
    net_weight_pic: '净重图片',
    bearing_test_pic: '承重检测图片',
    water_content_test_pic: '含水量检测图片',
    inspection_complete_pic: '',
    contract_sku_pic: '合同图片',
    factory_environment_pic: '工厂环境图片',
    factory_sample_room_pic: '工厂环境图片',
    factory_other_pic: '工厂其他图片',
    accessory_bar_code_pic: '配件条码',
    accessory_mark_pic: '配件唛头',
    accessory_num_pic: '配件数量',
    accessory_details_pic: '配件箱细节图',
    accessory_shipping_mark_pic:'配件箱唛头',
    accessory_size_pic_length:'配件箱长度',
    accessory_size_pic_width:'配件箱宽度',
    accessory_size_pic_height:'配件箱高度',
    accessory_gross_weight_pic:'配件箱毛重'
};
